Repository Ultraschall/ultraschall-portable, pull requests merged in 2018-03, with the labels that each got.

#10 Play from mouse Cursor auch auf Tracks
  reaper-mouse.ini
Labels: enhancement

#25 ultraclok.lua gelöscht und aufgeräumt
  Scripts/ultraclock.lua
  reaper-kb.ini
  reaper.ini
Labels: US6, cleanup

#32 #16 zoom out to region at cursor position
  Scripts/ultraschall_zoom_to_region_at_edit_cursor.lua
  reaper-kb.ini
Labels: #16, enhancement
